spring:
  application:
    name: user-microservice
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/userdb
    username: myuser
    password: secret
  flyway:
    clean-on-validation-error: true
    baseline-on-migrate: true
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
      flywaydb:
        core: DEBUG
server:
  port: 8081
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
